n_frames: 1000000
n_steps: 5000
batch_size: 128
phase_init: 'linear'
lr_factor: 0.5
lr_camera: 0.1
lr_human: 0.01
lr_instance: 0.001
lr_phase: 0.00001
opt_human: adam
wd_human: 0.001
h_dim: 500
monotonic_network_n_nodes: 200
loss: mse_robust
weight_vp_loss: 0
weight_gmm_loss: 0.5
start_phase: 0
out_dir: shared_out/20221008/default
user: 'kcjacksonwang'
tmp_dir: '/scratch/users/wangkua1/tmp'
label_type: 'op'
model_version: 1
warmup_step: 0
instance_code_size: 10
opt_cam_step: 1000
run_hmr: 0