exp_dir: 'data/exps/mymocap_baseball_pitch'
videos:
  # root_dir: ''
  names: 
    ['baseball_pitch.0.mp4',
    'baseball_pitch.1.mp4',
    'baseball_pitch.2.mp4',
    'baseball_pitch.3.mp4',
    'baseball_pitch.4.mp4',
    'baseball_pitch.5.mp4',
    'baseball_pitch.6.mp4',
    'baseball_pitch.7.mp4']