exp_dir: '/home/groups/syyeung/wangkua1/nemo/exps/mymocap_tennis_serve'
videos:
  root_dir: '/home/groups/syyeung/wangkua1/data/mymocap/trimmed1'
  names: 
    ['tennis_serve.0.mp4',
    'tennis_serve.1.mp4',
    'tennis_serve.2.mp4',
    'tennis_serve.3.mp4',
    'tennis_serve.4.mp4',
    'tennis_serve.5.mp4',
    'tennis_serve.6.mp4',
    'tennis_serve.7.mp4']