exp_dir: '/home/groups/syyeung/wangkua1/nemo/exps/mymocap_tennis_swing'
videos:
  root_dir: '/home/groups/syyeung/wangkua1/data/mymocap/trimmed1'
  names: 
    ['tennis_swing.0.mp4',
    'tennis_swing.1.mp4',
    'tennis_swing.2.mp4',
    'tennis_swing.3.mp4',
    'tennis_swing.4.mp4',
    'tennis_swing.5.mp4',
    'tennis_swing.6.mp4',
    'tennis_swing.7.mp4']